### ISSUE TITLE
null is not an object (evaluating "picker._init")

### ISSUE THREAD

**Issue by mahdipc** [mldb/rn-persian-date-picker#1]
I use 
`  <View
        style={{
          flex: 1,
          backgroundColor: "blue",
          justifyContent: "center",
          alignItems: "center"
        }}
      >
        <TouchableOpacity onPress={() => this.picker.showPicker()}>
          <View style={{ height: 80, width: 180, backgroundColor: "red" }}>
            <Text>
              {/* {selectedDate.format("jYYYY/jMM/jDD")} //for more formats and */}
              1400/12/1
            </Text>
          </View>
        </TouchableOpacity>        
        <PersianDatePicker
          type="Jalali"
          yearCount={10}
          onConfirm={date => this.setState({ selectedDate: date })}
          ref={ref => (this.picker = ref)}
        />
      </View>`
and show error null is not an object (evaluating "picker._init")

**Comment by mldb** [comment]
@mahdipc Please make sure [react-native-picker](https://github.com/beefe/react-native-picker) linked correctly.
