### ISSUE TITLE
onPickerCancel not work!!

### ISSUE THREAD

**Issue by mojtabadarzi** [mldb/rn-persian-date-picker#2]
when i call a function in **onPickerCancel**,  that doesn't work!!

**Comment by mldb** [comment]
@Moji0098 That issue is fixed in [1.0.5](https://www.npmjs.com/package/rn-persian-date-picker)

**Comment by mojtabadarzi** [comment]
```
<PersianDatePicker
      type="Jalali"
      yearCount={10}
      onConfirm={date => {
      this.setState({ selectedDate: date, date: false });
      console.log(this.refs['PICKER'].isOpen());
      }}
     onPickerCancel={() => { alert(99)}}
      />
```

i add an alert in **onPickerCancel** prop but that doesn't work yet , plz help me !

**Comment by mldb** [comment]
@Moji0098 in your package.json check datePicker version. it must to be 1.0.5

**Comment by mojtabadarzi** [comment]
@mldb .. thats worked. tnx  alot .. boj boj
